### PR TITLE
Added arch PKGBUILDs

### PR DESCRIPTION
**Pull request by katherlee**
I've been maintaining these simple scripts for Arch on the beloved arch user repository (AUR), though I no longer use them myself because of the compiler compatibility check. They were created long ago and really just for the simplest testing purposes. I think it might be useful to also put them here just to keep track.

### CODE REVIEW

**Comment by mwallerb** [comment]
Code looks good.  Only question is, how do we sync this with upstream (AUR)?

**Comment by katherlee** [comment]
Not sure if git submodules would work, since the AUR git repository needs
maintainer's (aka mine) SSH key for push permissions. I can check later for
any other options.

**Comment by mwallerb** [comment]
> Not sure if git submodules would work, since the AUR git repository needs maintainer's (aka mine) SSH key for push permissions

Maybe the other way then, i.e., update AUR and then have this repository "downstream"?

**Comment by katherlee** [comment]
Sounds like the only way we can do. Could git submodules work for this
purpose?

**Review by galexv — APPROVED** [review]
Looks good for me, but without ArchLinux i cannot test it :)

**Comment by egull** [comment]
same here – no way to test. But I'd say put it in, it may be useful for someone.

**Review by egull — APPROVED** [review]

**Comment by galexv** [comment]
> Sounds like the only way we can do. Could git submodules work for this
purpose?

Submodules, figuratively speaking, "symlink" another repo to the "parent" repo; and they need additional actions from users. I wonder if ["git subtree"](https://andrey.nering.com.br/2016/git-submodules-vs-subtrees/) approach will do better?

**Comment by egull** [comment]
Guys, I think you're overthinking this. I would only actively maintain this if we have enough users. For now let's put it here and leave it 'as is' in case it is useful for others.

**Comment by katherlee** [comment]
In case these don't work for whoever uses them from the AUR they will just
let me know through AUR. These are not super complex and super popular
anyways so I could just maintain by hand. Testing is doable with Travis and
Docker but I don't think it's really necessary for now.

**Pull request merged**
